spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

encryptor:
  key: ${JASYPT_KEY}

server:
  env: blue