spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(E7PZalPrLJMD3El73w0aNpnxAM+ilDUOxcl8CzZ8KiW4BP6EbKzxH3kRAdDNovsouqS8DO5sJ20=)
    username: root
    password: ENC(WVWFm5ztFfCLQzDKrZEZ4Q==)

  data:
    redis:
      host: 127.0.0.1
      port: 6379

    mongodb:
      host: localhost
      port: 27017
      username: ENC(GsCHiWIS/SjA7HliN3PtovpxB3yKKszJ)
      password: ENC(iUd5g5W+lE5rQO7uhUbQFkjvH+P5RUsN)
      database: ENC(qffKQ59Gd3EuH3G+7puCY/1Oubdbdb5F)

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

server:
  env: local
  port: 8080
  serverAddress: localhost

serverName: localhost
logging:
  level:
    com.carrot.carrotmarketclonecoding: DEBUG

websocket:
  origin: http://localhost:3000