spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(E7PZalPrLJMD3El73w0aNpnxAM+ilDUOxcl8CzZ8KiW4BP6EbKzxH3kRAdDNovsouqS8DO5sJ20=)
    username: root
    password: ENC(WVWFm5ztFfCLQzDKrZEZ4Q==)

  data:
    redis:
      host: 127.0.0.1
      port: 6379

    mongodb:
      uri: mongodb://carrot-market:ekgns0508@localhost:27017/carrot-market

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

server:
  env: local
  port: 8080
  serverAddress: localhost

serverName: localhost
logging:
  level:
    com.carrot.carrotmarketclonecoding: DEBUG

websocket:
  origin: http://127.0.0.1:3000
  rabbitmq:
    host: 127.0.0.1
    port: 61613
    username: guest
    password: guest