spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(1O5W6jYYhS843ppW75fyn1FnjaCmUhtB32BfcleuFiWB0LU7GNip3tu1TKQ1bXSBKPXdhA/EGwk=)
    username: root
    password: ENC(IodgSOc+Fl9zsU7t261DauMaJCjRPSNq)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

encryptor:
  key: ${JASYPT_KEY}

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: localhost

---

spring:
  config:
    activate:
      on-profile: blue

server:
  env: blue
  port: 8080
  serverAddress: 3.34.206.95

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  env: green
  port: 8081
  serverAddress: 3.34.206.95

serverName: green_server

---
