spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

encryptor:
  key: ${JASYPT_KEY}

server:
  env: blue

sse:
  timeout: 1800000

s3:
  board:
    bucket: ENC(bNnIVCrcukSCn+ewUyarhrco4Y6GDvwgUwtPhk/CcpRwGd3waQzxCA==)
    accessKey: ENC(9I+FNe3mBV4sCcP+wF5Wo1E0tWxa5I6Qh2VpT0nHzuU=)
    secretKey: ENC(h6QDcliPmdblNeU+SluXUxywb09NhatUUjRI9RJoaUcFkCOSieRxNcp9SXjQ1gWjjFufORPP2BA=)

kakao:
  client_id: ENC(3lReUAOOcDY3yjrs6RSPlfC4b4axnlefsmQbitKNXlt0QtmGxTmqcjRRP462SRox)
  admin-key: ENC(XX6kopdlBAf5/uJgp2P8qWu1nDjxQ3wL+UWnWFA8zm5BDas5s1PI7lPYO7wnJZf1)

jwt:
  secret: ENC(AZSMHtQVuCDzJNRt1ln9wKpeKm13cB6U9zIp23MOjjyBNIOqa+X7lMeAo8ki+bmW)
  expiration_time: ENC(Lo7/s4mCESUiz0GI8/WYGA==)
  refresh_expiration_time: ENC(k/35hOfhQC6TeZV6bs7KwhQo3I844ujZ)

logging:
  level:
    com.carrot.carrotmarketclonecoding: DEBUG