spring:
  config:
    activate:
      on-profile: green

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(1fJobeB0AOBZnenFlGS4Z466OfwxX1dW7Pu46+StIwo39EnbS5UxDuK3YJAcE8qGoT0qVdH/8VU=)
    username: root
    password: ENC(IodgSOc+Fl9zsU7t261DauMaJCjRPSNq)

  data:
    redis:
      host: ENC(PgnZGrO2VsW7JQAPvnYD7spp5X0nxFWX)
      port: 6379

  jpa:
    show-sql: false

server:
  env: green
  port: 8081
  serverAddress: ENC(dXcnoqAIp/O+aKQGMpLwNJ66ajoubJLH)

serverName: green_server

kakao:
  client_id: ENC(3lReUAOOcDY3yjrs6RSPlfC4b4axnlefsmQbitKNXlt0QtmGxTmqcjRRP462SRox)
  redirect_uri: ENC(WvpjgCPvXXjgl/3C5daeUdnQ3rupSqr+l7JbiJTNgSortNlpDAo5e8Lu7e468DQM)