spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(uTzRBPefL0bFrpGZxOWWNGL9Nw5Uyn+18hnaixjjKyMy6WUV9jnkiKluYhwC6ns0BXwsLRdzY3qupYb033VJqQ==)
    username: root
    password: ENC(IodgSOc+Fl9zsU7t261DauMaJCjRPSNq)

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

server:
  env: local
  port: 8080
  serverAddress: localhost

serverName: localhost